theme: minima
title: Michaels SQL Tips
author: Michael Fiedler
email: sommersby17@web.de
description: > # this means to ignore newlines until "baseurl:"
  Microsoft SQL Tips Tricks zu always on et al 

# social links
twitter_username: mjfheartonsleeve
github_username:  michi1860m

show_excerpts: true # set to false to remove excerpts on the homepage
